{
  "error": "'return' outside of function (1:0)"
}